services:
  web:
    networks:
      - projectcloak
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: frontend/
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: backend/
          target: /app
          ignore:
            - build/
            - bin/
            - .gradle/
    ports:
      - "8080:8080"
  
  postgres:
    container_name: postgres
    networks:
      - projectcloak
    image: "postgres:17.5-alpine3.21"
    ports: 
      - "5432:5432"
    env_file:
      - ./backend/.env
  
  postgres-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
     - projectcloak
    env_file:
      - ./backend/.env

# networks
networks:
  projectcloak:
    driver: bridge 
  